spring:
  application:
    name: spring-cloud-gateway
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    perfer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
